import {
  TrendingUp,
  ShieldCheck,
  PieChart,
  Landmark,
  Briefcase,
  Globe,
  FileText,
  BadgePercent,
  Users,
  Building2,
  ChartNoAxesColumn,
  PiggyBank,
  Wheat,
  RefreshCw,
  Lock
} from "lucide-react";

export const PRODUCTS_DATA = [
  {
    id: "Equity",
    slug: "equity",
    title: "Equities",
    iconPath: "/images/icon/menu/Equity 1.svg",
    tagline: "SELL",
    mainTitle: "No One Understands Equities, as We Do",
    shortDescription: "A captivating avenue for returns. Remember: buy right, hold tight.",
    description1: "Backed by a thorough research and comprehensive analysis, our ‘Equities’ division lets you trade across equities and exchanges. Driven by the passion to succeed, our equity experts strive to maximize your returns while minimize risks in this uncertain yet, exciting Indian Financial Markets.",
    description2: "From comprehensive insights into the equity markets to live stock prices, from days’ top gainers and losers to recommended stock picks and more - we got you covered, all!",
    featuresTitle: "Why Invest in Equities with Ratnakar?",
    features: [
      "Equity SIP Feature - A disciplined approach that helps you invest in key stocks, periodically",
      "Open your trading account in just 24 hours - Quick and hassle-free",
      "Real time portfolio monitoring",
      "Tailormade alerts to help you buy or sell preferred stocks, just at right price",
    ],
    imageSrc: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=2070&auto=format&fit=crop",
    buttonText: "Open Your Trading Account",
  },
  {
    id: "Derivatives",
    slug: "derivatives",
    title: "Derivatives",
    iconPath: "/images/icon/menu/derivatives 1.svg",
    tagline: "HEDGE",
    mainTitle: "Derivates Done Well with Ratnakar",
    shortDescription: "Leverage your position and hedge risks against unfavorable market movements.",
    description1: "With derivatives, investors can enjoy the liquidity and flexibility of equity markets while safeguard their investments against the future risk.",
    description2: "At Ratnakar, with investments in Derivatives, we enable to leverage your current position and hedge the risk by safeguarding your investments against potential losses of future.\n\nWe facilitate Currency Futures, Currency Trading, as well as the quintessential forms of derivative trading, Futures and Options.\n\nWe facilitate arbitrage, hedging, margin trade and all so that you make profits, you deserve.",
    featuresTitle: "Why Ratnakar?",
    features: [
      "We make F&O trading simpler and easier",
      "Our advisory services equip investors with knowledge and techniques to succeed",
      "Derivative reports and recommendations, that may yield good returns with lesser risk",
    ],
    imageSrc: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=2070&auto=format&fit=crop",
    buttonText: "Know More / Contact Us Today",
  },
  {
    id: "Mutual",
    slug: "mutual-funds",
    title: "Mutual Funds",
    iconPath: "/images/icon/menu/mutual funds 1.svg", tagline: "GROW",
    mainTitle: "Mutual Funds Sahi Hai, with Ratnakar",
    shortDescription: "A pool of small investments working together to achieve common financial goals.",
    description1: "In recent years, Mutual Funds have emerged as smart and viable alternative to stock markets. A professionally and skillfully managed investment option with flexibility to invest in equities, debt, government bonds, industry sectors and segments of your choice",
    description2: "Our wide and reliable network of affiliates backed by our proprietary research and advisory driven recommendations help mutual funds investors grow their wealth while keeping a tab on their goal attainment.\n\nSo, if you’re looking at saving tax, growing your wealth with minimal risk OR looking at long-term investments, our mutual fund affiliates help you accomplish all, with ease.",
    featuresTitle: "Ratnakar Advantage - When You Invest in Mutual Funds",
    features: [
      "Safe and secure investments - All Mutual Funds are registered with SEBI",
      "Portfolio diversification helps you minimize risk",
      "Choice and flexibility of choosing funds to meet your investment needs and financial goals",
      "Dedicated customer support to meet your tailormade needs",
    ],
    imageSrc: "/images/photorealistic-money-with-plant.jpg",
    buttonText: "Start Investing Today",
  },
  {
    id: "Commodities",
    slug: "commodities",
    title: "Commodities",
    iconPath: "/images/icon/menu/commodities 1.svg",
    tagline: "DIVERSIFY",
    mainTitle: "Commodities Checked Well with Ratnakar",
    shortDescription: "Lucrative market trading providing effective risk management and hedging tools.",
    description1: "A right mix of equities and commodities in your investment portfolio can help you benefit with attractive returns, while reducing or hedging the overall risk",
    description2: "At Ratnakar, we trade in commodities only through the client-based business and not the ‘proprietary trade’.\n\nWe help our clients invest in the commodities futures trading through MCX and NCDEX exchanges under standard contracts.\n\nWe facilitate trading in spot markets (commodities bought / sold for immediate delivery) or in futures market (commodities traded as derivatives).",
    featuresTitle: "Why Ratnakar?",
    features: [
      "We make client-based business in commodities trading simpler and easier",
      "Our commodity research equips investors with knowledge to gain profits at minimal risk",
    ],
    imageSrc: "https://images.unsplash.com/photo-1621504450181-5d356f61d307?q=80&w=2000&auto=format&fit=crop",
    buttonText: "Know More / Contact Us Today",
  },
  {
    id: "NRIs",
    slug: "nris",
    title: "NRIs",
    iconPath: "/images/icon/menu/company 1.svg",
    tagline: "CONNECT",
    mainTitle: "Investing in India Made Simpler with Ratnakar",
    shortDescription: "Comprehensive investment options for foreign nationals, backed by extensive research.",
    description1: "If you’re a foreign national and live abroad OR you’re a Non-Resident Indian (NRI) investor, Ratnakar Securities offers a comprehensive range of investment options for you. Backed by our extensive research and a dedicated team that understands your needs, we turn your investments in opportunity to prosper.",
    description2: "Here are the investment options you can explore with us;\n\nFinancial Advisors\nOur qualified team of financial advisors can help you invest in stocks of Indian companies, in a secondary market. By investing in mutual funds, you can benefit by indirect participation in the stock market.\n\nReal Estate Investments\nOur Real Estate expert team offers you an excellent opportunity to invest in the blooming real estate market in India via investment in commercial or residential properties. From the research to connecting you with the buyer / seller to helping you with all the contractual and legal formalities, we’ll be there for all.",
    featuresTitle: "Why invest with Ratnakar?",
    features: [
      "A dedicated team that understands your needs and your goals",
      "Thorough research backed by our extensive network of affiliates",
      "Availability of resources per your convenience",
      "A tailormade investment options to suit your risk & return profile",
    ],
    imageSrc: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=2074&auto=format&fit=crop",
    buttonText: "Apply for our NRI Services Today",
  },
  {
    id: "Wealth",
    slug: "wealth-management",
    title: "Wealth Management",
    iconPath: "/images/icon/menu/invesment 1.svg",
    tagline: "PROTECT",
    mainTitle: "Comprehensive Wealth Management Services for Every Stage of Life",
    shortDescription: "Managing and growing your wealth through every stage of your life.",
    description1: "At every stage of your lifetime, your financial goals may vary. At Ratnakar, we understand you and your priorities and go extent in protecting, managing and growing your wealth with our well-structured and comprehensive suite of wealth management services.",
    description2: "At Ratnakar Securities, we understand the value of your time and the opportunities it holds for you.\n\nYour personal finances will get the attention they deserve while you attend to your business and professional needs. Our tailor-made Wealth Management Services created exclusively for valued customers like you for managing and enhancing your wealth. Your dedicated Relationship (Wealth) Manager is backed by a structured research and a team of financial experts to bring you best-in-class financial solutions for your different needs.",
    featuresTitle: "Why Ratnakar?",
    features: [
      "Safe and secure investments - Backed by thorough research and tailormade to your needs",
      "Diverse investments to help you minimize risk",
      "Wider network of Financial Service Providers (Affiliates) for your Investments, Insurance and Loan needs",
      "Choice and flexibility of choosing investment and protection solution to meet your financial needs",
      "Dedicated Relationship (Wealth) Manager to support you 24X7, 365 days",
    ],
    imageSrc: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=2070&auto=format&fit=crop",
    buttonText: "Click Here to Enroll",
  },
  {
    id: "SLBM",
    slug: "slbm",
    title: "SLBM",
    iconPath: "/images/icon/menu/annual return 1.svg",
    tagline: "LEND",
    mainTitle: "Why let your stocks sit idle when they can earn ‘extra’?",
    shortDescription: "Lend your stocks or borrow to increase liquidity and benefit from downturns.",
    description1: "Security Landing and Borrowing Scheme\nBy helping you trade through Security Landing and Borrowing Schemes (SLBM), Ratnakar Securities can help you lend your own stocks while borrowing the ones, you don’t own! SLBM helps you increase your liquidity while helping you in benefit from the downturn by short selling your stocks.",
    description2: "Our SLBM services include thorough equity research, monitoring selective stocks / schemes and most importantly the advice that always ticks profits and higher return on your investments.",
    featuresTitle: "Why invest with Ratnakar?",
    features: [
      "Comprehensive investment and advisory for you and for your business",
      "We take care of all the headache from lending to borrowing so that you can sit, relax and benefit",
      "A tailormade SLBM options to suit your risk & return profile",
    ],
    imageSrc: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=2036&auto=format&fit=crop",
    buttonText: "Learn More",
  },
  {
    id: "HNIs",
    slug: "hnis",
    title: "HNIs",
    iconPath: "/images/icon/menu/leadership 1.svg",
    tagline: "PREMIUM",
    mainTitle: "Exclusive Services for High Net-Worth Individuals",
    shortDescription: "Tailormade investment solutions with a dedicated Relationship Manager for guidance.",
    description1: "For our High Net-Worth Individual (HNI) clients, we offer an exclusive and personalized approach to wealth management and investment.",
    description2: "With a dedicated Relationship Manager, we ensure that your financial portfolio is given the utmost attention and tailored to your specific financial goals and risk appetite. Our HNI services provide comprehensive access to premium investment opportunities, structured products, and expert advisory.",
    featuresTitle: "Why Choose Ratnakar for HNIs?",
    features: [
      "Dedicated Relationship Manager providing continuous support",
      "Access to premium and exclusive investment opportunities",
      "Tailor-made portfolio management and strategic financial planning",
      "Expert advisory and deep market insights"
    ],
    imageSrc: "https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=2069&auto=format&fit=crop",
    buttonText: "Join Our Premium Services",
  },
  {
    id: "Bonds",
    slug: "bonds",
    title: "Bonds",
    iconPath: "/images/icon/menu/Bonds 1.svg",
    tagline: "SECURE",
    mainTitle: "We Help You ‘Bond’ with Your Money",
    shortDescription: "Secure mode of investment backed by our deep understanding of debt markets.",
    description1: "Bonds are gradually emerging as effective yet a very secure mode of investments in recent times. Ratnakar Securities understand ‘Bonds’ like none and with our deep understanding of the debt markets and unmatched research, we help you invest and mitigate risk by investing into bonds that meet your goals.",
    description2: "Why Bonds?\nBonds tend to offer the highest and most reliable income streams, even at times when prevailing rates are low\nWith diversified investments in bonds, investors can reduce the volatility and preserve capital\nBonds allow protection of principal, as a diversified bond portfolio is much less likely to suffer large losses in a short period\nCertain bonds also offer a potential tax advantage when invested into government owned bonds\nBy investing in ‘Bonds’, you not only earn a ‘predetermined interest’ at regular intervals but also earn an assured ‘principal amount’ at the end of the maturity period.",
    featuresTitle: "Why invest with Ratnakar?",
    features: [
      "Safe and secure investments - Backed by a thorough research and recommendations",
      "Investing in ‘Bonds’ helps you minimize risk while assuring, assured returns",
      "Choice and flexibility of choosing bonds to meet your investment needs and financial goals",
      "Dedicated customer support to meet your tailormade needs",
    ],
    imageSrc: "https://images.unsplash.com/photo-1607863680198-23d4b2565df0?q=80&w=2070&auto=format&fit=crop",
    buttonText: "Start Investing Today",
  },
];
